config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :screen_settings
  root :to => 'screen_settings#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/screen_setting.rb
class ScreenSetting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/screen_settings_controller.rb
class ScreenSettingsController < ApplicationController

  # GET /screen_settings
  # GET /screen_settings.json
  def index
    @screen_settings = ScreenSetting.where(:screen_name=>"Home")
    render json: @screen_settings.first
  end

  # GET /screen_settings/1
  # GET /screen_settings/1.json
  def show
    @screen_setting = ScreenSetting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @screen_setting }
    end
  end

  # GET /screen_settings/new
  # GET /screen_settings/new.json
  def new
    @screen_setting = ScreenSetting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @screen_setting }
    end
  end

  # GET /screen_settings/1/edit
  def edit
    @screen_setting = ScreenSetting.find(params[:id])
  end

  # POST /screen_settings
  # POST /screen_settings.json
  def create
    @screen_setting = ScreenSetting.new(params[:screen_setting])

    respond_to do |format|
      if @screen_setting.save
        format.html { redirect_to @screen_setting, notice: 'Screen setting was successfully created.' }
        format.json { render json: @screen_setting, status: :created, location: @screen_setting }
      else
        format.html { render action: "new" }
        format.json { render json: @screen_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /screen_settings/1
  # PUT /screen_settings/1.json
  def update
    @screen_setting = ScreenSetting.find(params[:id])

    respond_to do |format|
      if @screen_setting.update_attributes(params[:screen_setting])
        format.json { render json: @screen_setting, status: :ok }
      else
        format.json { render json: @screen_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screen_settings/1
  # DELETE /screen_settings/1.json
  def destroy
    @screen_setting = ScreenSetting.find(params[:id])
    @screen_setting.destroy

    respond_to do |format|
      format.html { redirect_to screen_settings_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/screen_settings_helper.rb
module ScreenSettingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelTripper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/screen_settings/_form.html.erb
<%= form_for(@screen_setting) do |f| %>
  <% if @screen_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screen_setting.errors.count, "error") %> prohibited this screen_setting from being saved:</h2>

      <ul>
      <% @screen_setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :screen_name %><br />
    <%= f.text_field :screen_name %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :font %><br />
    <%= f.text_field :font %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/screen_settings/edit.html.erb
<h1>Editing screen_setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @screen_setting %> |
<%= link_to 'Back', screen_settings_path %>

app/views/screen_settings/home.html.erb
<div id="main-content" class="container">
	<div class="jumbotron font-changable color-changable">
		<h1>My First SPA Page</h1>
		<p>
			Resize this responsive page to see the effect!
		</p>
	</div>
	<div class="row font-changable color-changable">
		<div class="col-sm-4">
			<h3>Column 1</h3>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit...
			</p>
			<p>
				Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
			</p>
		</div>
		<div class="col-sm-4">
			<h3>Column 2</h3>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit...
			</p>
			<p>
				Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
			</p>
		</div>
		<div class="col-sm-4">
			<h3>Column 3</h3>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit...
			</p>
			<p>
				Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
			</p>
		</div>
	</div>
	<div class="row" style="text-align: center">
		<div class="btn-group">
			<a id="change-title" class="btn btn-primary" data-toggle="modal" data-target="#myModal1"> Change Document UI Settings </a>
		</div>
	</div>

</div>
<!-- Modal 1 -->
<div id="myModal1" class="modal fade " role="dialog">
	<div class="modal-dialog">

		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					&times;
				</button>
				<h4 class="modal-title">Change Document UI Settings</h4>
			</div>
			<div class="modal-body">
				<!-- <p>
				Enter the title you want to change.
				<input type="text" style="width: 96%;" value="" id="id-input-title">
				</p> -->

				<form class="form-horizontal" id="update_setting">
					<fieldset>
						<div class="control-group">
							<label for="id-role" class="control-label">Title</label>
							<div class="controls">
								<input type="text" placeholder="Enter Page Title Here" id="screen_setting_title" name="title" class="form-control">
							</div>
						</div>
						<input disabled="disabled" type="hidden" style="display:none" name="name"  id="screen_setting_name" >
						<input disabled="disabled" type="hidden" style="display:none" name="id"  id="screen_setting_id" >

						<div class="control-group">
							<label for="id-role" class="control-label">Font Family</label>
							<div class="controls">
								<select id="screen_setting_font" class="form-control"  name="font">
									<option style="font-family: 'Comic Sans MS'">Comic Sans MS</option>
									<option style="font-family: Arial">Arial</option>
									<option style="font-family: 'Times New Roman'">Times New Roman</option>
									<option style="font-family: 'verdana, arial, helvetica, sans-serif'">verdana, arial, helvetica, sans-serif</option>
									<option style="font-family: 'tangerine'">Tangerine</option>
									<option style="font-family: 'tahoma'">Tahoma</option>
								</select>
							</div>
						</div>

						<div class="control-group " >
							<label for="id-email" class="control-label">Background Color</label>
							<div class="controls">
								<input type="text" class="form-control jscolor" value="transparent"  placeholder="Enter text color here" id="screen_setting_color" name="color">
							</div>
						</div>

						<!-- <div class="control-group " >
						<label for="id-email" class="control-label">Background Color</label>
						<div class="controls">
						<input type="text"  placeholder="Enter text color here" id="screen_setting_bg_color" class="form-control" name="bg_color">
						<input type="text"  class="jscolor" value="ab2567">
						</div>
						</div> -->

					</fieldset>
				</form>
			</div>
			<div class="modal-footer">
				<a id="id-update-title" data-dismiss="modal" class="btn btn-primary"> <i id="id-btn-workflow-add-progress"></i><span>Change</span> </a>
				<button type="button" id="close-setting-modal" class="btn btn-default" data-dismiss="modal">
					Close
				</button>
			</div>

		</div>
	</div>
</div>

app/views/screen_settings/index.html.erb
<h1>Listing screen_settings</h1>

<table>
  <tr>
    <th>Screen name</th>
    <th>Color</th>
    <th>Title</th>
    <th>Font</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @screen_settings.each do |screen_setting| %>
  <tr>
    <td><%= screen_setting.screen_name %></td>
    <td><%= screen_setting.color %></td>
    <td><%= screen_setting.title %></td>
    <td><%= screen_setting.font %></td>
    <td><%= link_to 'Show', screen_setting %></td>
    <td><%= link_to 'Edit', edit_screen_setting_path(screen_setting) %></td>
    <td><%= link_to 'Destroy', screen_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Screen setting', new_screen_setting_path %>

app/views/screen_settings/new.html.erb
<h1>New screen_setting</h1>

<%= render 'form' %>

<%= link_to 'Back', screen_settings_path %>

app/views/screen_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Screen name:</b>
  <%= @screen_setting.screen_name %>
</p>

<p>
  <b>Color:</b>
  <%= @screen_setting.color %>
</p>

<p>
  <b>Title:</b>
  <%= @screen_setting.title %>
</p>

<p>
  <b>Font:</b>
  <%= @screen_setting.font %>
</p>


<%= link_to 'Edit', edit_screen_setting_path(@screen_setting) %> |
<%= link_to 'Back', screen_settings_path %>